version: "3.1"

services:
  db:
    image: citygram/data
    networks:
      - citygram
    ports:
      - "25432:5432"
    container_name: citygram_db
  redis:
    image: redis:3.0.3
    networks:
      - citygram
    container_name: citygram_redis
  citygram:
    image: citygram/citygram
    environment:
      DATABASE_URL: postgres://postgres@citygram_db/citygram_development
    ports:
      - "9292:9292"
    networks:
      - citygram
networks:
  citygram: